# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["hkakehashi+demo@fastly.com"]
description = "Sample Compute@Edge app that modifies HTML returned from https://example.com on the fly"
language = "javascript"
manifest_version = 2
name = "ecp-rewrite-html-js"
service_id = ""

[local_server]
  [local_server.backends]
    [local_server.backends.backend_1]
      url = "https://example.com"

[setup]
  [setup.backends]
    [setup.backends.backend_1]
      address = "example.com"
      port = 443
