# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["hrmsk66@gmail.com"]
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "javascript"
manifest_version = 2
name = "rewrite-html-js"
service_id = "2A6yvGYr63GAPSDqoWw8mH"

[local_server]

  [local_server.backends]

    [local_server.backends.example_com]
      url = "https://example.com"

[setup]

  [setup.backends]

    [setup.backends.example_com]
      address = "example.com"
      port = 443
